# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: web/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files # prevents giant files from being committed.
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
      - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang.
      - id: check-json # checks json files for parseable syntax.
      - id: check-shebang-scripts-are-executable # ensures that (non-binary) files with a shebang are executable.
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-symlinks # checks for symlinks which do not point to anything.
      - id: check-vcs-permalinks # ensures that links to vcs websites are permalinks.
      - id: check-yaml # checks yaml files for parseable syntax.
      - id: destroyed-symlinks # detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
      - id: detect-private-key # detects the presence of private keys.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: file-contents-sorter # sorts the lines in specified files (defaults to alphabetical). you must provide list of target files as input in your .pre-commit-config.yaml file.
      - id: fix-byte-order-marker # removes utf-8 byte order marker.
      - id: mixed-line-ending # replaces or checks mixed line ending.
      - id: pretty-format-json # This hook sets a standard for formatting JSON files.
        exclude: .vscode
      - id: requirements-txt-fixer # sorts entries in requirements.txt.
      - id: trailing-whitespace # trims trailing whitespace.

  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: (dtrx)|(\.(py)$)

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.18.3
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

  # keep this in front of prettier, in case they're incompatible
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: markdown-toc
        args: [--no-firsth1, -i, --bullets=-]
        require_serial: true
        # only apply this to the top-level README.md
        files: \./README\.md

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier
        args: [--write]
        files: \.(js|ts|jsx|tsx|css|less|html|json|markdown|md|yaml|yml)$
        exclude: .vscode

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.0.0
    hooks:
      - id: setup-cfg-fmt
