# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-added-large-files  # Prevent giant files from being committed
    -   id: check-case-conflict  # Check for files that would conflict in case-insensitive filesystems
    -   id: check-executables-have-shebangs  # Ensures that (non-binary) executables have a shebang.
    -   id: check-json  # This hook checks json files for parseable syntax.
    -   id: check-yaml  # This hook checks yaml files for parseable syntax.
    -   id: end-of-file-fixer  # Ensures that a file is either empty, or ends with one newline.
    -   id: pretty-format-json  # This hook sets a standard for formatting JSON files.
    -   id: trailing-whitespace  # This hook trims trailing whitespace.
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    -   id: isort
